# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: pull_request_fork

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-workflow:
    name: Build workflow from matrix
    if: github.repository != 'NVIDIA/cccl'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      base_sha: ${{ steps.export-pr-info.outputs.base_sha }}
      pr_number: ${{ steps.export-pr-info.outputs.pr_number }}
      workflow: ${{ steps.build-workflow.outputs.workflow }}
      ci_enabled: ${{ steps.export-flags.outputs.ci_enabled }}
      matrix_enabled: ${{ steps.export-flags.outputs.matrix_enabled }}
      vdc_enabled: ${{ steps.export-flags.outputs.vdc_enabled }}
      docs_enabled: ${{ steps.export-flags.outputs.docs_enabled }}
    steps:
      - name: Export workflow flags
        id: export-flags
        run: |
          output() { echo "$1=$2" | tee -a "${GITHUB_OUTPUT}"; }

          output ci_enabled     "true" # This job only runs when CI is enabled (see `if:` field)
          output matrix_enabled "${{ !contains(github.event.head_commit.message, '[skip-matrix]') }}"
          output vdc_enabled    "${{ !contains(github.event.head_commit.message, '[skip-vdc]') }}"
          output docs_enabled   "${{ !contains(github.event.head_commit.message, '[skip-docs]') }}"
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Lookup PR info
        id: get-pr-info
        uses: nv-gha-runners/get-pr-info@main
      - name: Export PR info
        id: export-pr-info
        run: |
          echo "base_sha=${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}" | tee -a "${GITHUB_OUTPUT}"
          echo "pr_number=${{ fromJSON(steps.get-pr-info.outputs.pr-info).number }}" | tee -a "${GITHUB_OUTPUT}"
      - name: Build workflow
        # Skip building the matrix when disabled, but still gather PR info for downstream jobs
        if: steps.export-flags.outputs.matrix_enabled == 'true'
        id: build-workflow
        uses: ./.github/actions/workflow-build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ steps.export-pr-info.outputs.pr_number }}
          allow_override: "true"
          inspect_changes_script: 'ci/inspect_changes.sh'
          inspect_changes_base_sha: ${{ steps.export-pr-info.outputs.base_sha }}
          workflows: 'pull_request_fork'

  dispatch-groups-linux-two-stage:
    name: ${{ needs.build-workflow.outputs.ci_enabled == 'true' && matrix.name || 'Fork CI (skipped)' }}
    if: >-
      ${{
        needs.build-workflow.outputs.ci_enabled == 'true' &&
        needs.build-workflow.outputs.matrix_enabled == 'true' &&
        toJSON(fromJSON(needs.build-workflow.outputs.workflow)['linux_two_stage']['keys']) != '[]'
      }}
    needs: build-workflow
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJSON(needs.build-workflow.outputs.workflow)['linux_two_stage']['keys'] }}
    uses: ./.github/workflows/workflow-dispatch-two-stage-group-linux.yml
    with:
      pc-array: ${{ toJSON(fromJSON(needs.build-workflow.outputs.workflow)['linux_two_stage']['jobs'][matrix.name]) }}
    secrets: inherit

  dispatch-groups-windows-two-stage:
    name: ${{ needs.build-workflow.outputs.ci_enabled == 'true' && matrix.name || 'Fork CI (skipped)' }}
    if: >-
      ${{
        needs.build-workflow.outputs.ci_enabled == 'true' &&
        needs.build-workflow.outputs.matrix_enabled == 'true' &&
        toJSON(fromJSON(needs.build-workflow.outputs.workflow)['windows_two_stage']['keys']) != '[]'
      }}
    needs: build-workflow
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJSON(needs.build-workflow.outputs.workflow)['windows_two_stage']['keys'] }}
    uses: ./.github/workflows/workflow-dispatch-two-stage-group-windows.yml
    with:
      pc-array: ${{ toJSON(fromJSON(needs.build-workflow.outputs.workflow)['windows_two_stage']['jobs'][matrix.name]) }}
    secrets: inherit

  dispatch-groups-linux-standalone:
    name: ${{ needs.build-workflow.outputs.ci_enabled == 'true' && matrix.name || 'Fork CI (skipped)' }}
    if: >-
      ${{
        needs.build-workflow.outputs.ci_enabled == 'true' &&
        needs.build-workflow.outputs.matrix_enabled == 'true' &&
        toJSON(fromJSON(needs.build-workflow.outputs.workflow)['linux_standalone']['keys']) != '[]'
      }}
    needs: build-workflow
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJSON(needs.build-workflow.outputs.workflow)['linux_standalone']['keys'] }}
    uses: ./.github/workflows/workflow-dispatch-standalone-group-linux.yml
    with:
      job-array: ${{ toJSON(fromJSON(needs.build-workflow.outputs.workflow)['linux_standalone']['jobs'][matrix.name]) }}
    secrets: inherit

  dispatch-groups-windows-standalone:
    name: ${{ needs.build-workflow.outputs.ci_enabled == 'true' && matrix.name || 'Fork CI (skipped)' }}
    if: >-
      ${{
        needs.build-workflow.outputs.ci_enabled == 'true' &&
        needs.build-workflow.outputs.matrix_enabled == 'true' &&
        toJSON(fromJSON(needs.build-workflow.outputs.workflow)['windows_standalone']['keys']) != '[]'
      }}
    needs: build-workflow
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        name: ${{ fromJSON(needs.build-workflow.outputs.workflow)['windows_standalone']['keys'] }}
    uses: ./.github/workflows/workflow-dispatch-standalone-group-windows.yml
    with:
      job-array: ${{ toJSON(fromJSON(needs.build-workflow.outputs.workflow)['windows_standalone']['jobs'][matrix.name]) }}
    secrets: inherit

  verify-workflow:
    name: ${{ needs.build-workflow.outputs.ci_enabled == 'true' && 'Verify and summarize workflow results' || 'Fork CI (skipped)' }}
    if: >-
      ${{
        needs.build-workflow.outputs.ci_enabled == 'true' &&
        always() &&
        !cancelled() &&
        needs.build-workflow.outputs.matrix_enabled == 'true'
      }}
    needs:
      - build-workflow
      - dispatch-groups-linux-two-stage
      - dispatch-groups-windows-two-stage
      - dispatch-groups-linux-standalone
      - dispatch-groups-windows-standalone
    permissions:
      contents: read
      pull-requests: write # Posts a comment back to the PR.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check workflow success
        id: check-workflow
        uses: ./.github/actions/workflow-results
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ needs.build-workflow.outputs.pr_number }}

  verify-devcontainers:
    name: ${{ needs.build-workflow.outputs.ci_enabled == 'true' && 'Verify Dev Containers' || 'Fork CI (skipped)' }}
    needs: build-workflow
    if: >-
      ${{
        needs.build-workflow.outputs.ci_enabled == 'true' &&
        needs.build-workflow.outputs.vdc_enabled == 'true'
      }}
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/verify-devcontainers.yml
    with:
      base_sha: ${{ needs.build-workflow.outputs.base_sha }}

  docs-build:
    name: ${{ needs.build-workflow.outputs.ci_enabled == 'true' && 'Build and deploy documentation preview' || 'Fork CI (skipped)' }}
    needs: build-workflow
    if: >-
      ${{
        needs.build-workflow.outputs.pr_number &&
        needs.build-workflow.outputs.ci_enabled  == 'true' &&
        needs.build-workflow.outputs.docs_enabled == 'true'
      }}
    permissions:
      contents: write
      pull-requests: write
      pages: write
    uses: ./.github/workflows/build-docs.yml
    with:
      destination_dir: docs/pr-preview/pr-${{ needs.build-workflow.outputs.pr_number }}
      pr_number: ${{ needs.build-workflow.outputs.pr_number }}
